### ISSUE TITLE
getUrl fails for alternative URLs using 'urls' meta data

### ISSUE THREAD

**Issue by thesec** [Hypercubed/docpad-plugin-geturl#1]
When I define an alternative URL for a document and request it, getUrl still returns the `site.URL + relativeOutPath`, not the actual URL.

e.g. `http://localhost/docs/offset/shared/some.html`where the request was for `http://localhost/docs/some`

**Comment by thesec** [comment]
... trying to resolve and answer my question from http://stackoverflow.com/questions/19252513/how-to-get-the-relative-url-for-the-rendered-document

fyi

**Comment by Hypercubed** [comment]
What should it do if alternative urls are defined... there is not a one to one mapping.

**Comment by Hypercubed** [comment]
Closing some old issues.  Please reopen if you still need this.
