### ISSUE TITLE
Error When Running test

### ISSUE THREAD

**Issue by oleersoy** [Hypercubed/docpad-plugin-geturl#3]
Here are my steps:

ole@tungsten:~/Experiment/test$ git clone https://github.com/Hypercubed/docpad-plugin-geturl.git
Cloning into 'docpad-plugin-geturl'...
remote: Counting objects: 99, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 99 (delta 45), reused 99 (delta 45)
Unpacking objects: 100% (99/99), done.
Checking connectivity... done
ole@tungsten:~/Experiment/test$ cd docpad-plugin-geturl/
ole@tungsten:~/Experiment/test/docpad-plugin-geturl$ npm install
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/joe-reporter-console
npm http GET https://registry.npmjs.org/joe
npm http GET https://registry.npmjs.org/docpad-plugin-eco
npm http GET https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/joe-reporter-console
npm http 304 https://registry.npmjs.org/joe
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/docpad-plugin-eco
npm http 304 https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/eco
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/taskgroup
npm http 304 https://registry.npmjs.org/eco
npm http 304 https://registry.npmjs.org/cli-color
npm http 304 https://registry.npmjs.org/taskgroup
npm http GET https://registry.npmjs.org/ambi
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/strscan
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/strscan
npm http 304 https://registry.npmjs.org/ambi
npm http GET https://registry.npmjs.org/typechecker
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/typechecker

> typechecker@2.0.8 preinstall /home/ole/Experiment/test/docpad-plugin-geturl/node_modules/joe/node_modules/taskgroup/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/next-tick
chai@1.6.1 node_modules/chai

coffee-script@1.6.3 node_modules/coffee-script

docpad-plugin-eco@2.0.2 node_modules/docpad-plugin-eco
└── eco@1.1.0-rc-3 (strscan@1.0.1)

joe@1.2.0 node_modules/joe
└── taskgroup@3.1.2 (eventemitter2@0.4.13, ambi@2.0.0)

joe-reporter-console@1.2.1 node_modules/joe-reporter-console
└── cli-color@0.2.3 (es5-ext@0.9.2, memoizee@0.2.6)
ole@tungsten:~/Experiment/test/docpad-plugin-geturl$ make compile
./node_modules/.bin/coffee -o out/ -c src/
ole@tungsten:~/Experiment/test/docpad-plugin-geturl$ make test
./node_modules/.bin/coffee -o out/ -c src/
npm test

> docpad-plugin-geturl@2.1.1 test /home/ole/Experiment/test/docpad-plugin-geturl
> node ./out/geturl.test.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'docpad'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ole/Experiment/test/docpad-plugin-geturl/out/geturl.test.js:3:3)
    at Object.<anonymous> (/home/ole/Experiment/test/docpad-plugin-geturl/out/geturl.test.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0
make: **\* [test] Error 1

**Comment by oleersoy** [comment]
I added docpad 6 to the devDependencies and now it runs fine;
  "devDependencies": {
    "docpad": "6",
    "coffee-script": "~1.6.2",
    "docpad-plugin-eco": "~2.0.2",
    "joe": "~1.2.0",
    "joe-reporter-console": "~1.2.1",
    "chai": "~1.6.1"
  },

**Comment by Hypercubed** [comment]
Hmmm.. do we really need to do this.  Docpad 6 is already listed in the engines section and should be installed globally. Maybe peerDependencies?

**Comment by Hypercubed** [comment]
Closing some old issues.  Please reopen if you still need this.
