### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by jaarong** [Hypercubed/docpad-plugin-geturl#6]
Obviously, I have a gross misunderstanding of how Eco or Docpad functions, because I cannot get this work.  I have a site.url set, and here is my code: 

```
<% @getBlock("scripts").add([@getUrl('/bower_components/jquery/dist/jquery.min.js'), @getUrl('/bower_components/foundation/js/foundation.min.js'), @getUrl('/bower_components/picturefill/dist/picturefill.min.js'), @getUrl('/scripts/app.js'), @getUrl('/scripts/script.js')]).toHTML() %>
```

What am I doing wrong?

**Comment by Hypercubed** [comment]
Closing some old issues.  Please reopen if you still need this.
